### PR TITLE
Updates for Laravel 5

### PR DESCRIPTION
**Pull request by impleri**
While updating composer.json seems sufficient enough, This includes updating ViewFactory::make to match what's in illuminate/view and updating dependencies (Mockery and PHPUnit).

### CODE REVIEW

**Comment by impleri** [comment]
Guessing by the comment in #42, I'm pinging @robclancy for visibility without creating a separate issue.

Also, are you looking for a co-maintainer?

**Comment by robclancy** [comment]
This one was failing which is why I never looked at it. The other PR did barely anything so I was under the impression that was all that was needed. I will properly look into all this later today and make a proper release.

**Comment by impleri** [comment]
It was failing the StyleCI checks because the current codebase doesn't pass StyleCI ;)

**Comment by robclancy** [comment]
And never will, I think I integrated that to test it out and forgot t leave
it.

**Comment by impleri** [comment]
Poking the beehive...

**Comment by barryvanveen** [comment]
@robclancy, is there a plan for supporting Laravel 5.1 in the near future?

If I could assist in any way, please let me know.

**Comment by darkwinternight** [comment]
Poke :)

**Comment by robclancy** [comment]
No one has actually told me what doesn't work, I have used this recently in a 5.x project. I am looking to start a new project where I use it more as using it makes it far easier for me to know what it needs etc.

**Pull request closed without merging**
